import React from "react";
import Link from "next/link";
import Image from "next/image";
import { Metadata } from "next";
import { CheckCircle, ArrowRight, Sun, ShieldCheck, Zap, Sparkles, Phone, Mail, Award, Check, Calendar, Wrench, Coins, Users } from "lucide-react";
import ContactForm from "@/components/ContactForm";
import SolarCalculator from "@/components/SolarCalculator";
import FaqAccordion from "@/components/FaqAccordion";
import GoogleReviews from "@/components/GoogleReviews";
import ZeroInvestmentCalculator from "@/components/ZeroInvestmentCalculator";
import SolutionsCountdownTimer from "@/components/SolutionsCountdownTimer";
import BreadcrumbSchema from "@/components/BreadcrumbSchema";
import FAQSchema from "@/components/FAQSchema";


export const metadata: Metadata = {
  title: "Residential Solar & Home Rooftop Energy Solutions | SunLynk Solar",
  description: "Save up to 90% on home electricity bills with SunLynk Solar. We design and install high-efficiency residential solar systems and hybrid battery storage with subsidy assistance.",
  keywords: [
    "residential solar panel installation",
    "home solar panels",
    "rooftop solar subsidy",
    "on-grid solar homes",
    "hybrid solar systems",
    "residential solar cost",
    "PM Surya Ghar subsidy registration",
    "home solar installer India"
  ],
};

export default function HomesPage() {
  const benefits = [
    {
      title: "Significant reduction in electricity bills",
      desc: "Save up to 90% on domestic power costs by shifting your daytime load to clean solar energy.",
      icon: Coins
    },
    {
      title: "Customized system design for maximum generation",
      desc: "Our engineers design structures optimized precisely for your rooftop geometry and shade-free zones.",
      icon: Sparkles
    },
    {
      title: "Government subsidy assistance for eligible homeowners",
      desc: "Complete documentation and approvals under the PM Surya Ghar Yojana processed by our team.",
      icon: Award
    },
    {
      title: "Real-time performance monitoring",
      desc: "Track energy generation, self-consumption, and grid exports directly from your smartphone.",
      icon: Zap
    },
    {
      title: "Professional installation and long-term support",
      desc: "Built by certified technicians using premium components for long-term safety and maintenance.",
      icon: Wrench
    },
    {
      title: "Reliable solar solutions built for 25+ years of operation",
      desc: "Long-term product warranty provides absolute security for decades of clean energy generation.",
      icon: ShieldCheck
    }
  ];

  const solutions = [
    {
      title: "On-Grid Solar Systems",
      desc: "Ideal for homes connected to steady utility grids. Export surplus solar energy through net metering and watch your monthly bill shrink to near zero.",
      points: ["Best Return on Investment (ROI)", "Govt subsidy up to ₹1,08,000", "Net metering segment clearance"],
      bg: "bg-emerald-50/20 border-emerald-100"
    },
    {
      title: "Hybrid Solar Systems with Backup",
      desc: "Combines high-generation solar panels with storage battery banks. Rest assured that your refrigerators, lights, and essential appliances stay powered during load-shedding.",
      points: ["Continuous backup protection", "Smart load optimization", "Energy independence during blackouts"],
      bg: "bg-blue-50/20 border-blue-100"
    },
  ];

  const faqs = [
    {
      id: 0,
      question: "What is the subsidy for residential solar in Lucknow under PM Surya Ghar Yojana?",
      answer: "Under the PM Surya Ghar Muft Bijli Yojana, residential consumers can receive a subsidy of ₹30,000 per kW for up to 2 kW systems, and an additional ₹18,000 for the 3rd kW, capping at a maximum of ₹1,08,000 for systems of 3 kW or higher capacity. SunLynk handles all the registration and approval paperwork for you."
    },
    {
      id: 1,
      question: "How long does it take to recover the installation cost (payback period)?",
      answer: "Home solar systems typically achieve payback within 4 to 5 years. After this initial payback period, the electricity generated by your solar rooftop is practically free, yielding substantial savings for the remaining 20+ years of panel life."
    },
    {
      id: 2,
      question: "Can I run my AC, geysers, and heavy appliances on solar?",
      answer: "Yes, definitely. Our systems are engineered to handle all residential loads. In an On-Grid configuration, the solar power supplements your grid energy seamlessly. For Hybrid systems, we design battery banks specifically to support heavy inductive loads such as ACs and water pumps during grid outages."
    },
    {
      id: 3,
      question: "What happens on cloudy or rainy days?",
      answer: "Solar panels convert daylight (diffused light) into electricity, so they will continue to generate power on cloudy days, albeit at a reduced efficiency (typically 10-25% of peak capacity). The system automatically pulls any shortfall from the grid or battery back-up, ensuring no interruption to your power supply."
    }
  ];

  return (
    <div className="bg-white text-dark">
      <BreadcrumbSchema
        items={[
          { name: "Home", item: "/" },
          { name: "Solutions", item: "/#solutions" },
          { name: "Homes", item: "/solutions/homes" }
        ]}
      />
      <FAQSchema
        items={faqs.map((faq) => ({
          question: faq.question,
          answer: faq.answer
        }))}
      />
      <section className="relative overflow-hidden bg-white">

        {/* ── Desktop-only background image (bottom-left) ── */}
        <div className="absolute left-0 bottom-0 w-[62%] h-[80%] z-0 pointer-events-none overflow-hidden hidden lg:block">
          <Image
            src="/new_assets/homes_banner.webp"
            alt="Residential solar rooftop background"
            fill
            className="object-cover object-bottom"
            priority
          />
          <div className="absolute inset-0 bg-gradient-to-t from-transparent via-white/40 to-white" />
          <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/20 to-white" />
        </div>

        {/* ── Desktop-only right panel ── */}
        <div className="absolute top-0 right-0 h-full w-[45%] bg-[#F1F5F9]/60 hidden lg:block z-0" />

        {/* ── Mobile background tint (very subtle) ── */}
        <div className="absolute inset-0 bg-gradient-to-b from-slate-50/60 to-white lg:hidden z-0 pointer-events-none" />

        <div className="max-w-7xl mx-auto relative z-10 px-4 sm:px-6 md:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 lg:gap-12 items-start min-h-[unset] lg:min-h-[600px]">

            {/* ── Left: Headline + badge ── */}
            <div className="lg:col-span-7 relative flex flex-col justify-between text-left h-screen lg:h-auto pt-16 pb-0 lg:py-16 -mx-4 sm:-mx-6 md:-mx-8 lg:mx-0 lg:px-0">

              {/* Mobile-only background image banner */}
              <div className="lg:hidden absolute inset-0 pointer-events-none z-0 overflow-hidden select-none">
                <Image
                  src="/new_assets/home_hero_mobile.webp"
                  alt="Mobile solar background"
                  fill
                  className="object-cover"
                  priority
                />
                {/* Dark overlay for superior text contrast on mobile */}
                <div className="absolute inset-0 bg-linear-to-b from-black/10 via-black/50 to-black/80" />
              </div>

              {/* Text content container */}
              <div className="relative z-10 flex flex-col gap-4 sm:gap-5 px-4 sm:px-0 mb-6 lg:mb-0 mt-auto">
                {/* Star badge */}
                <div className="flex items-center gap-2 bg-white/10 backdrop-blur-sm border border-white/15 rounded-full py-1.5 px-3.5 self-start text-[11px] sm:text-xs font-bold text-white shadow-sm lg:bg-white lg:border-gray-200 lg:text-slate-600">
                  <span className="text-amber-400 lg:text-amber-500 text-sm leading-none">★★★★★</span>
                  <span>Rated 4.8 on Google</span>
                  <span className="hidden sm:inline text-white/30 lg:text-slate-300">|</span>
                  <span className="hidden sm:inline">12,000+ Happy Homes</span>
                </div>

                {/* Headline */}
                <h1 className="text-[2rem] sm:text-4xl lg:text-5xl font-black leading-[1.12] tracking-tight text-white lg:text-slate-950">
                  Save up to 90%{" "}
                  <span className="block sm:inline">
                    <br className="hidden sm:block lg:hidden" />
                    <span className="text-primary">on your electricity bills.</span>
                  </span>
                </h1>

                {/* Sub-copy — visible on mobile, hidden on desktop to keep it clean */}
                <p className="text-sm sm:text-base text-white/80 lg:text-slate-500 leading-relaxed max-w-sm lg:hidden">
                  India's most trusted solar partner. PM Surya Ghar subsidy handled
                  end-to-end. Zero hassle, guaranteed savings.
                </p>

                {/* Trust pills row — mobile only */}
                <div className="flex flex-wrap gap-2 lg:hidden">
                  {["PM Subsidy up to ₹1,08,000", "30-yr Performance Guarantee", "Free Site Survey"].map((t) => (
                    <span
                      key={t}
                      className="text-[11px] font-semibold text-white bg-white/10 border border-white/10 rounded-full px-3 py-1"
                    >
                      ✓ {t}
                    </span>
                  ))}
                </div>
              </div>

              {/* Countdown Timer with creative tagline (Only visible on mobile) */}
              <div className="relative z-10 w-full lg:hidden">
                <SolutionsCountdownTimer />
              </div>
            </div>

            {/* ── Right: Form card ── */}
            <div className="lg:col-span-5 w-full pt-2 pb-8 sm:pb-10 lg:py-16">
              {/*
              On mobile the form card sits directly below the headline with
              comfortable top spacing. On desktop it aligns to the right panel.
            */}
              <div className="bg-white rounded-2xl sm:rounded-3xl shadow-[0_4px_32px_rgba(0,0,0,0.10)] border border-slate-200/60 overflow-hidden">
                <ContactForm hideTabs={true} defaultTab="residential" />
              </div>

              {/* Mobile-only reassurance line below form */}
              <p className="mt-3 text-center text-[11px] text-slate-400 lg:hidden">
                🔒 Your data is safe. No spam, ever.
              </p>
            </div>

          </div>
        </div>
      </section>


      {/* Structured Solution Choices */}
      <section className="py-20 bg-white border-y border-gray-100">
        <div className="max-w-7xl mx-auto px-4 md:px-8">

          <div className="text-center max-w-3xl mx-auto mb-16 flex flex-col items-center gap-3">
            <div className="inline-flex items-center gap-2">
              <span className="h-[2px] w-6 bg-primary"></span>
              <span className="text-base uppercase tracking-wider font-bold text-primary">Solutions Available</span>
              <span className="h-[2px] w-6 bg-primary"></span>
            </div>
            <h2 className="text-3xl md:text-5xl font-black text-gray-900 leading-tight">
              Tailored Residential Configurations
            </h2>
            <p className="text-sm sm:text-base text-gray-500 max-w-2xl leading-relaxed">
              We engineer layouts using only Tier-1 components designed to maximize power generation under local temperature variations.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-7xl mx-auto">
            {solutions.map((sol, index) => (
              <div
                key={index}
                className={`border rounded-xl p-6 sm:p-8 flex flex-col justify-between hover:shadow-xl transition-all duration-300 group ${sol.bg}`}
              >
                <div className="flex flex-col gap-5">
                  <div className="w-12 h-12 rounded-2xl bg-white shadow flex items-center justify-center text-primary border border-gray-150">
                    <Sun size={24} />
                  </div>
                  <h3 className="text-xl font-extrabold text-gray-900 group-hover:text-primary transition-colors">
                    {sol.title}
                  </h3>
                  <p className="text-xs sm:text-sm text-gray-600 leading-relaxed text-justify">
                    {sol.desc}
                  </p>
                  <ul className="flex flex-col gap-3 mt-2 text-left">
                    {sol.points.map((pt, pIdx) => (
                      <li key={pIdx} className="flex gap-2 items-center text-xs font-bold text-gray-700">
                        <span className="w-4 h-4 rounded-full bg-primary/10 flex items-center justify-center shrink-0 text-primary">
                          <Check size={10} className="stroke-[3]" />
                        </span>
                        <span>{pt}</span>
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="mt-8 pt-4 border-t border-gray-150">
                  <Link href="/#solar-calculator" className="inline-flex items-center gap-1.5 text-xs font-black uppercase text-primary hover:underline">
                    <span>Explore Savings Calculator</span>
                    <ArrowRight size={14} className="group-hover:translate-x-0.5 transition-transform" />
                  </Link>
                </div>
              </div>
            ))}
          </div>

        </div>
      </section>

      {/* Zero Investment EMI Calculator */}
      <ZeroInvestmentCalculator />



      {/* The SunLynk Journey Section */}
      <section className="py-24 bg-white border-b border-gray-100 overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 md:px-8">

          {/* Header */}
          <div className="text-center max-w-3xl mx-auto mb-20 flex flex-col items-center gap-3">
            <div className="inline-flex items-center gap-2">
              <span className="h-[2px] w-6 bg-primary"></span>
              <span className="text-base uppercase tracking-wider font-bold text-primary">Your Journey</span>
              <span className="h-[2px] w-6 bg-primary"></span>
            </div>
            <h2 className="text-3xl md:text-5xl font-black text-gray-900 leading-tight">
              The SunLynk Journey
            </h2>
            <p className="text-sm sm:text-base text-gray-500 max-w-2xl leading-relaxed">
              Transitioning to solar power is simple and seamless. Here is how we get your rooftop power station up, running, and saving you money.
            </p>
          </div>

          {/* Steps Wrapper */}
          <div className="relative">
            {/* Desktop Timeline Connector Line */}
            <div className="hidden lg:block absolute top-[52%] left-[12%] right-[12%] h-[3px] bg-gradient-to-r from-yellow-400/70 via-yellow-400/70 to-yellow-400/70 -translate-y-1/2 z-0"></div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 relative z-10">

              {/* Step 1: Book Visit */}
              <div className="group relative bg-white border border-gray-100 hover:border-gray-200 p-6 rounded-xl transition-all duration-300 shadow-xl flex flex-col items-center text-center h-full justify-between">
                <div className="flex flex-col items-center w-full">
                  <div className="absolute -top-5 left-6 bg-[#f9b623] text-white w-10 h-10 rounded-full flex items-center justify-center font-black text-sm border-4 border-white shadow-md z-20">
                    1
                  </div>
                  <div className="relative w-full h-44 rounded-xl overflow-hidden mb-6 border border-gray-100 shadow-inner group-hover:shadow-md transition-shadow">
                    <img
                      src="/assets/images/journey_book_visit_indian.png"
                      alt="Book a Free Visit"
                      className="object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                    <div className="absolute inset-0"></div>
                  </div>
                  <h3 className="text-lg font-black text-gray-900 mb-2">Book Visit</h3>
                  <p className="text-xs text-gray-500 leading-relaxed">
                    Book your free site assessment. We check your roof space, orientation, and past electricity bills.
                  </p>
                </div>
              </div>

              {/* Step 2: Get Design */}
              <div className="group relative bg-white border border-gray-100 hover:border-gray-200 p-6 rounded-xl transition-all duration-300 shadow-xl flex flex-col items-center text-center h-full justify-between">
                <div className="flex flex-col items-center w-full">
                  <div className="absolute -top-5 left-6 bg-primary text-white w-10 h-10 rounded-full flex items-center justify-center font-black text-sm border-4 border-white shadow-md z-20">
                    2
                  </div>
                  <div className="relative w-full h-44 rounded-xl overflow-hidden mb-6 border border-gray-100 shadow-inner">
                    <img
                      src="/assets/images/journey_get_design_indian.png"
                      alt="Get 3D Design"

                      className="object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/10 to-transparent"></div>
                  </div>
                  <h3 className="text-lg font-black text-gray-900 mb-2">Get Design</h3>
                  <p className="text-xs text-gray-500 leading-relaxed">
                    Receive a customized 3D solar rendering. We optimize the structures for shade-free zones and maximum sunlight exposure.
                  </p>
                </div>
              </div>

              {/* Step 3: Installation */}
              <div className="group relative bg-white border border-gray-200 p-6 rounded-xl transition-all duration-300 shadow-xl flex flex-col items-center text-center h-full justify-between">
                <div className="flex flex-col items-center w-full">
                  <div className="absolute -top-5 left-6 bg-[#f9b623] text-white w-10 h-10 rounded-full flex items-center justify-center font-black text-sm border-4 border-white shadow-md z-20">
                    3
                  </div>
                  <div className="relative w-full h-44 rounded-xl overflow-hidden mb-6 border border-gray-100 shadow-inner group-hover:shadow-md transition-shadow">
                    <img
                      src="/assets/images/journey_installation_indian.png"
                      alt="Professional Installation"

                      className="object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/10 to-transparent"></div>
                  </div>
                  <h3 className="text-lg font-black text-gray-900 mb-2">Installation</h3>
                  <p className="text-xs text-gray-500 leading-relaxed">
                    Fast and professional installation. Our certified team mounts structures, solar panels, inverters, and connects net metering.
                  </p>
                </div>
              </div>

              {/* Step 4: Start Saving */}
              <div className="group relative bg-white border border-gray-200 p-6 rounded-xl transition-all duration-300 shadow-xl flex flex-col items-center text-center h-full justify-between">
                <div className="flex flex-col items-center w-full">
                  <div className="absolute -top-5 left-6 bg-[#f9b623] text-white w-10 h-10 rounded-full flex items-center justify-center font-black text-sm border-4 border-white shadow-md z-20">
                    4
                  </div>
                  <div className="relative w-full h-44 rounded-xl overflow-hidden mb-6 border border-gray-100 shadow-inner group-hover:shadow-md transition-shadow">
                    <img
                      src="/assets/images/journey_start_saving_indian.png"
                      alt="Start Saving Energy"
                      className="object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/10 to-transparent"></div>
                  </div>
                  <h3 className="text-lg font-black text-gray-900 mb-2">Start Saving</h3>
                  <p className="text-xs text-gray-500 leading-relaxed">
                    Switch on your system! Instantly generate clean energy, export excess to the grid, and watch your electricity bills drop.
                  </p>
                </div>
              </div>

            </div>         </div>
        </div>
      </section>

      {/* Capacity Reference Table Section */}
      <section className="py-24 bg-slate-200 border-y border-slate-100 overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 md:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">

            {/* Left Column: Title and details */}
            <div className="lg:col-span-4 flex flex-col gap-6 text-left">
              <div className="flex flex-col gap-3">
                <div className="inline-flex items-center gap-2">
                  <span className="h-[1px] w-6 bg-primary"></span>
                  <span className="text-base uppercase tracking-wider font-bold text-primary">
                    Capacity Reference
                  </span>
                  <span className="h-[1px] w-6 bg-primary"></span>

                </div>
                <h2 className="text-3xl sm:text-5xl font-black text-slate-900 leading-tight uppercase mt-2">
                  From 1 kW to 10 kW
                </h2>
                <p className="text-sm sm:text-base text-slate-500 leading-relaxed text-justify mt-2">
                  Home systems range from compact setups to large residential arrays. We size your residential rooftop solar panels to align with your family's actual monthly unit consumption, rather than just filling up empty roof space.
                </p>
              </div>

              {/* Example Card */}
              <div className="bg-white border border-slate-200/60 rounded-2xl p-6 shadow-md hover:shadow-lg transition-shadow duration-300">
                <span className="block text-xs font-extrabold text-slate-400 uppercase mb-2">
                  Example:
                </span>
                <p className="text-[11px] sm:text-xs text-slate-500 leading-relaxed">
                  A standard <strong className="text-slate-950 font-bold">3 kW</strong> home setup generates roughly <strong className="text-slate-950 font-bold">360 units</strong> of free electricity every month, ideal for offsetting the billing costs of a typical 3BHK Indian household running regular modern appliances.
                </p>
              </div>
            </div>

            {/* Right Column: Table */}
            <div className="lg:col-span-8 flex flex-col gap-4">
              <div className="w-full overflow-x-auto rounded-xl border border-slate-200/80 shadow-xl">
                <table className="w-full min-w-[700px] border-collapse bg-white text-left">
                  <thead>
                    <tr className="bg-gradient-to-r from-primary to-[#065F46] text-white">
                      <th className="p-5 text-[10px] font-extrabold uppercase tracking-wider border-r border-white/10">Capacity</th>
                      <th className="p-5 text-[10px] font-extrabold uppercase tracking-wider border-r border-white/10">Rooftop Area</th>
                      <th className="p-5 text-[10px] font-extrabold uppercase tracking-wider border-r border-white/10">Daily Generation</th>
                      <th className="p-5 text-[10px] font-extrabold uppercase tracking-wider border-r border-white/10">Monthly Units</th>
                      <th className="p-5 text-[10px] font-extrabold uppercase tracking-wider">Ideal For</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                    <tr className="hover:bg-emerald-50/20 transition-colors">
                      <td className="p-5 text-[12px] font-black text-primary border-r border-slate-100">1 kW</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~80-100 sq ft</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~4 units</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~120 units</td>
                      <td className="p-5 text-[12px] text-slate-500 font-medium">Small apartments, basic lighting loads</td>
                    </tr>
                    <tr className="hover:bg-emerald-50/20 transition-colors">
                      <td className="p-5 text-[12px] font-black text-primary border-r border-slate-100">2 kW</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~160-200 sq ft</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~8 units</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~240 units</td>
                      <td className="p-5 text-[12px] text-slate-500 font-medium">1-2 BHK homes, regional flats</td>
                    </tr>
                    <tr className="bg-emerald-50/30 hover:bg-emerald-50/50 transition-colors">
                      <td className="p-5 text-sm font-black text-primary border-r border-slate-100">
                        <div className="flex items-center gap-2">
                          <span>3 kW</span>
                        </div>
                      </td>
                      <td className="p-5 text-sm text-slate-600 border-r border-slate-100 font-semibold">~240-300 sq ft</td>
                      <td className="p-5 text-sm text-slate-600 border-r border-slate-100 font-semibold">~12 units</td>
                      <td className="p-5 text-sm text-slate-600 border-r border-slate-100 font-semibold">~360 units</td>
                      <td className="p-5 text-sm text-slate-900 font-bold">3 BHK homes (Most Popular Size)</td>
                    </tr>
                    <tr className="hover:bg-emerald-50/20 transition-colors">
                      <td className="p-5 text-[12px] font-black text-primary border-r border-slate-100">5 kW</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~400-500 sq ft</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~20 units</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~600 units</td>
                      <td className="p-5 text-[12px] text-slate-500 font-medium">Large independent floors, small villas</td>
                    </tr>
                    <tr className="hover:bg-emerald-50/20 transition-colors">
                      <td className="p-5 text-[12px] font-black text-primary border-r border-slate-100">10 kW</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~800-1,000 sq ft</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~40 units</td>
                      <td className="p-5 text-[12px] text-slate-600 border-r border-slate-100 font-semibold">~1,200 units</td>
                      <td className="p-5 text-[12px] text-slate-500 font-medium">Luxury bungalows, large country estates</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <p className="text-xs sm:text-sm text-slate-500 font-semibold text-center lg:text-left flex flex-wrap items-center justify-center lg:justify-start gap-1 mt-1">
                <span>Still not sure?</span>
                <a href="/#solar-calculator" className="text-emerald-700 hover:underline font-bold inline-flex items-center gap-1 transition-colors">
                  Calculate your solar requirement with our Solar Calculator
                  <ArrowRight size={14} className="animate-pulse" />
                </a>
              </p>
            </div>

          </div>
        </div>
      </section>

      <section className="py-16 bg-gray-1000 border-y border-gray-100 overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 md:px-8">

          {/* Mobile: images first, Desktop: side by side */}
          <div className="flex flex-col-reverse lg:grid lg:grid-cols-12 gap-10 lg:gap-16 items-center">

            {/* Left Column: Text + Why Choose Us Grid */}
            <div className="lg:col-span-7 flex flex-col gap-8">
              <div className="flex flex-col gap-3">
                <div className="inline-flex items-center gap-2">
                  <span className="h-[2px] w-6 bg-primary"></span>
                  <span className="text-base uppercase tracking-wider font-bold text-primary">Why Choose Us</span>
                  <span className="h-[2px] w-6 bg-primary"></span>
                </div>
                <h2 className="text-2xl sm:text-4xl md:text-4xl font-extrabold text-dark leading-tight text-left">
                  Why Partners & Homeowners <br className="hidden sm:inline" />
                  <span className="text-primary font-black">Choose SunLynk</span>
                </h2>
                <p className="text-sm sm:text-base text-gray-500 max-w-xl text-left">
                  We deliver top-tier engineering, long-term reliability, and guaranteed performance parameters for every solar solution.
                </p>
              </div>

              {/* Core Advantages Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 sm:gap-6 text-left">

                {/* Advantage 1 */}
                <div className="flex gap-4 group">
                  <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0 group-hover:bg-primary group-hover:text-white transition-all duration-300 shadow-sm">
                    <Users size={22} />
                  </div>
                  <div>
                    <h4 className="font-bold text-gray-900 text-[15px] sm:text-base mb-1 group-hover:text-primary transition-colors duration-300">
                      Experienced Team
                    </h4>
                    <p className="text-xs sm:text-sm text-gray-500 leading-relaxed">
                      10+ years of trusted engineering expertise delivering higher quality installations.
                    </p>
                  </div>
                </div>

                {/* Advantage 2 */}
                <div className="flex gap-4 group">
                  <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0 group-hover:bg-primary group-hover:text-white transition-all duration-300 shadow-sm">
                    <ShieldCheck size={22} />
                  </div>
                  <div>
                    <h4 className="font-bold text-gray-900 text-[15px] sm:text-base mb-1 group-hover:text-primary transition-colors duration-300">
                      25-Year Product Warranty
                    </h4>
                    <p className="text-xs sm:text-sm text-gray-500 leading-relaxed">
                      Long-term performance and product reliability warranty for absolute peace of mind.
                    </p>
                  </div>
                </div>

                {/* Advantage 4 */}
                <div className="flex gap-4 group">
                  <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0 group-hover:bg-primary group-hover:text-white transition-all duration-300 shadow-sm">
                    <Zap size={22} />
                  </div>
                  <div>
                    <h4 className="font-bold text-gray-900 text-[15px] sm:text-base mb-1 group-hover:text-primary transition-colors duration-300">
                      Quicker Project Execution
                    </h4>
                    <p className="text-xs sm:text-sm text-gray-500 leading-relaxed">
                      Swift design engineering, rapid execution, and seamless grid commissioning.
                    </p>
                  </div>
                </div>

                {/* Advantage 5 - spans full width on desktop */}
                <div className="flex gap-4 group ">
                  <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0 group-hover:bg-primary group-hover:text-white transition-all duration-300 shadow-sm">
                    <Sun size={22} />
                  </div>
                  <div>
                    <h4 className="font-bold text-gray-900 text-[15px] sm:text-base mb-1 group-hover:text-primary transition-colors duration-300">
                      Unit Generation Guarantee
                    </h4>
                    <p className="text-xs sm:text-sm text-gray-500 leading-relaxed max-w-xl">
                      We guarantee specified electricity output and pay ₹8/unit for any generation deficit.
                    </p>
                  </div>
                </div>

              </div>

              {/* CTA */}
              <div className="text-left">
                <a
                  href="/contact"
                  className="inline-flex items-center gap-2 bg-primary hover:bg-primary-hover text-white font-bold py-3 px-7 rounded-lg transition-all duration-300 shadow-lg shadow-primary/15 hover:shadow-primary/25 text-sm"
                >
                  Get Free Solar Consultation
                  <ArrowRight size={16} />
                </a>
              </div>
            </div>

            {/* Right Column: 2 Images Stacked Layout */}
            <div className="lg:col-span-5 relative w-full">
              <div className="grid grid-cols-2 gap-3 sm:gap-4">
                {/* Image 1 — Rooftop */}
                <div className="relative aspect-[3/4] rounded-2xl overflow-hidden shadow-lg border border-gray-100 group">
                  <Image
                    src="/assets/images/handle_rooftop.webp"
                    alt="Solar panels on Indian rooftop"
                    fill
                    className="object-cover group-hover:scale-105 transition-transform duration-700"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent" />
                </div>

                {/* Image 2 — Team + stat badge */}
                <div className="relative aspect-[3/4] rounded-2xl overflow-hidden shadow-lg border border-gray-100 group mt-6 sm:mt-8">
                  <Image
                    src="/assets/images/teams.png"
                    alt="SunLynk solar installation team"
                    fill
                    className="object-cover group-hover:scale-105 transition-transform duration-700"
                  />
                  <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent" />
                </div>
              </div>

              {/* Floating Stat Badge */}
              {/* <div className="absolute -bottom-4 left-1/2 -translate-x-1/2 bg-white border border-gray-100 rounded-xl shadow-lg px-5 py-3 flex items-center gap-3 z-20">
                      <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center">
                        <Sun className="w-5 h-5 text-primary" />
                      </div>
                      <div>
                        <span className="text-lg font-black text-gray-900 leading-none">40,000+</span>
                        <span className="block text-[10px] text-gray-500 font-semibold uppercase tracking-wide">Homes Solarized</span>
                      </div>
                    </div> */}
            </div>

          </div>
        </div>
      </section>

      {/* Creative Premium Benefits Grid */}
      <section className="py-20 bg-[#065F46]">
        <div className="max-w-7xl mx-auto px-4 md:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">

            {/* Left Column: Real Solar Image */}
            <div className="lg:col-span-5 relative w-full">
              <div className="relative aspect-[4/5] rounded-xl overflow-hidden shadow-xl border border-gray-150 group">
                {/* <video
                  src="/new_assets/_assist_video.mp4"
                  className="w-full h-full absolute inset-0 object-cover group-hover:scale-102 transition-transform duration-500"
                  autoPlay
                  muted
                  loop
                  playsInline
                /> */}
                <img src="/new_assets/modisolar.avif" alt="solar modi yojna" className="w-full h-full absolute inset-0 object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/50 via-transparent to-transparent pointer-events-none"></div>

                {/* Floating stat card on the image */}
                <div className="absolute bottom-6 left-6 right-6 bg-white/90 backdrop-blur-md border border-white/20 rounded-xl p-4 shadow-lg text-left">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0">
                      <Sparkles size={20} className="animate-pulse" />
                    </div>
                    <div>
                      <span className="block text-gray-950 font-black text-sm">PM Surya Ghar Yojana</span>
                      <span className="block text-[10px] text-gray-500 font-bold uppercase mt-0.5">Subsidy Support Assured</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Right Column: Key Benefits Text & Items */}
            <div className="lg:col-span-7 flex flex-col gap-6 text-left">
              <div className="flex flex-col gap-3">
                <div className="inline-flex items-center gap-2">
                  <span className="h-[2px] w-6 bg-primary"></span>
                  <span className="text-base uppercase tracking-wider font-bold text-primary">Key Benefits</span>
                  <span className="h-[2px] w-6 bg-primary"></span>
                </div>
                <h2 className="text-3xl sm:text-4xl font-black text-white leading-tight">
                  Designed for Reliability and Optimal Returns
                </h2>
                <p className="text-sm text-gray-200 leading-relaxed text-justify">
                  Transitioning to clean energy shouldn't be stressful. We ensure every panel operates at peak efficiency, utilizing top-tier engineering to yield reliable generation for 25+ years.
                </p>
              </div>

              {/* Benefits micro-grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {benefits.map((b, idx) => {
                  const IconComponent = b.icon;
                  return (
                    <div
                      key={idx}
                      className="bg-white border border-gray-100 p-5 rounded-2xl shadow-sm hover:shadow-lg hover:-translate-y-0.5 transition-all duration-300 text-left flex gap-4 items-start group"
                    >
                      <div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0 border border-primary/20 group-hover:bg-primary group-hover:text-white transition-all duration-300">
                        <IconComponent className="w-5 h-5" />
                      </div>
                      <div>
                        <h3 className="font-extrabold text-sm sm:text-base text-gray-950 group-hover:text-primary transition-colors duration-300">
                          {b.title}
                        </h3>
                        <p className="text-[11px] sm:text-xs text-gray-500 leading-relaxed mt-1">
                          {b.desc}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* Solar Savings Calculator */}
      {/* <SolarCalculator /> */}

      {/* Real Installations Showcase */}
      <GoogleReviews />


      {/* FAQ Section */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 md:px-8 grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">

          {/* FAQ Left Block */}
          <div className="lg:col-span-5 text-left flex flex-col gap-4 sticky top-24">
            <div className="inline-flex items-center gap-2">
              <span className="h-[2px] w-6 bg-primary"></span>
              <span className="text-base uppercase tracking-wider font-bold text-primary">FAQ</span>
              <span className="h-[2px] w-6 bg-primary"></span>
            </div>
            <h3 className="text-3xl md:text-5xl font-black text-gray-900 leading-tight">Frequently Asked Questions</h3>
            <p className="text-sm text-gray-500 leading-relaxed text-justify">
              Clear answers to the most common queries homeowners raise regarding panel durability, grid interfaces, and net-metering structures.
            </p>
            <div className="p-6 bg-slate-50 border border-gray-200/80 rounded-xl flex flex-col gap-3.5 mt-4">
              <span className="font-extrabold text-sm text-gray-800 block">Have specific queries?</span>
              <div className="flex flex-col gap-2">
                <a href="tel:+918573003001" className="flex items-center gap-2 text-xs font-bold text-gray-700 hover:text-primary transition-colors">
                  <Phone size={14} className="text-primary" />
                  <span>+91 8573003001</span>
                </a>
                <a href="mailto:info@sunlynksolar.com" className="flex items-center gap-2 text-xs font-bold text-gray-700 hover:text-primary transition-colors">
                  <Mail size={14} className="text-primary" />
                  <span>info@sunlynksolar.com</span>
                </a>
              </div>
            </div>
          </div>

          {/* FAQ Right Block Accordions */}
          <div className="lg:col-span-7 w-full">
            <FaqAccordion faqs={faqs} />
          </div>

        </div>
      </section>
    </div>
  );
}
